Updated all files for new name

diff --git a/.github/workflows/regression.yml b/.github/workflows/regression.yml
--- a/.github/workflows/regression.yml
+++ b/.github/workflows/regression.yml
@@ -54,7 +54,7 @@ jobs:
       with:
         python-version: '3.10'
     - run: |
-        pylint qas_editor --rcfile=$(git ls-files '.pylintrc') --output-format=text | tee ./pylint.log || pylint-exit $?
+        pylint OpenQAS --rcfile=$(git ls-files '.pylintrc') --output-format=text | tee ./pylint.log || pylint-exit $?
         echo "PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint.log)" >> $GITHUB_ENV
         
 
@@ -68,7 +68,7 @@ jobs:
         python-version: '3.10'
     - name: Lint with flake8
       run: |
-        echo "FLAKE_ERRORS=$(flake8 qas_editor --count --exit-zero --statistics --output-file ./flake8.log)" >> $GITHUB_ENV
+        echo "FLAKE_ERRORS=$(flake8 OpenQAS --count --exit-zero --statistics --output-file ./flake8.log)" >> $GITHUB_ENV
 
 
   pytest:
@@ -94,7 +94,7 @@ jobs:
     needs: [pylint, flake8, pytest]
     steps:
     - name: Create Pylint Badge
-      uses: LucasWolfgang/dynamic-badges-action@master
+      uses: Wolf359Stella/dynamic-badges-action@master
       with:
         auth: ${{ secrets.GIST_SECRET }}
         gistID: 344598a4a0f7b92a7889d998e33417c4
@@ -106,7 +106,7 @@ jobs:
         valColorRange: ${{ env.PYLINT_SCORE }}
       continue-on-error: true   
     - name: Create Flake8 Badge
-      uses: LucasWolfgang/dynamic-badges-action@master
+      uses: Wolf359Stella/dynamic-badges-action@master
       with:
         auth: ${{ secrets.GIST_SECRET }}
         gistID: 344598a4a0f7b92a7889d998e33417c4
@@ -119,7 +119,7 @@ jobs:
         invertColorRange: 1
       continue-on-error: true  
     - name: Create Pytest Badge
-      uses: LucasWolfgang/dynamic-badges-action@master
+      uses: Wolf359Stella/dynamic-badges-action@master
       with:
         auth: ${{ secrets.GIST_SECRET }}
         gistID: 344598a4a0f7b92a7889d998e33417c4
